# Generated by Django 5.0.6 on 2024-05-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producstmodel',
            old_name='title',
            new_name='name',
        ),
    ]
