# Generated by Django 5.0.6 on 2024-05-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_title_producstmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producstmodel',
            old_name='name',
            new_name='title',
        ),
    ]
