# Generated by Django 5.0.6 on 2024-05-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_producstmodel_test_producstmodel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='producstmodel',
            name='image2',
            field=models.ImageField(null=True, upload_to='product'),
        ),
    ]
