# Generated by Django 5.0.6 on 2024-05-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_producstmodel_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producstmodel',
            name='dicount',
            field=models.IntegerField(null=True),
        ),
    ]
