# Generated by Django 5.0.6 on 2024-05-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_producstmodel_dicount'),
    ]

    operations = [
        migrations.AddField(
            model_name='producstmodel',
            name='sizes',
            field=models.ManyToManyField(related_name='products', to='product.producuctschoissizemodel'),
        ),
    ]
