# Generated by Django 5.0.6 on 2024-06-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_commentsproductsmodle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producstmodel',
            options={},
        ),
    ]
