# Generated by Django 5.0.6 on 2024-06-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FedbackModelPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fedbacks', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fedback',
                'verbose_name_plural': 'Fedbacks',
            },
        ),
    ]
